task_01 commitment
TECHF5VE/TechMap-Works pull request #190
Opened 2021-11-09 08:51 UTC by C1ri007

2021-11-09 12:05 UTC, hamono requested changes
![image](https://user-images.githubusercontent.com/56852035/140921158-1aefb3aa-e0c3-45f3-91f7-356fc0255f33.png)
有些格式错误

2021-11-10 01:57 UTC, dgb1252 commented
格式还是有问题
![image](https://user-images.githubusercontent.com/56926598/141035324-83e052e3-f157-470e-b880-9a5dc7fd3178.png)
建议用markdown语法的严格模式（兼容性高），推荐typora这个markdown编辑器（可支持主题以及语法的配置）

2021-11-10 02:02 UTC, tagbug commented on 2021-Autumn/Backend/task_01/C1ri007/README.md
> +​    我用的是Ghelper，基本没有什么大问题，就是clone远程库到本地git的时候有些不稳定，可能会报错，只要多试几次就行了
挂代理的话在git上也要做相应的配置，配置代理ip和端口

2021-11-10 03:14 UTC, hamono requested changes

2021-11-10 03:14 UTC, hamono commented on 2021-Autumn/Backend/task_01/C1ri007/README.md
> +   **姓名：**丁晨凯 ~~aka.C1ri007~~
格式为：
````
**something**[space]other
````

需要空格

2021-11-10 04:13 UTC, dgb1252 commented
尽量还是不要用h5的标签，虽然支持使用标签，但这不是markdown的目的，最好用markdown语法。

2021-11-10 08:04 UTC, tagbug commented
写的还是挺不错的，加油💪

2021-11-10 11:42 UTC, hamono approved these changes

2021-11-10 11:42 UTC, merged